name: fl_jpush
description:  jpush plugin for flutter, only Android and IOS are supported
version: 1.0.0
repository: https://github.com/Wayaer/fl_jpush.git

environment:
  sdk: '>=2.12.1 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: fl.jpush
        pluginClass: JPushPlugin
      ios:
        pluginClass: JPushPlugin
